# Generated by Django 5.2.6 on 2025-09-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='source',
        ),
        migrations.AddField(
            model_name='quote',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='genre',
            field=models.CharField(choices=[('Книга', 'Книга'), ('Фильм', 'Фильм'), ('Музыка', 'Музыка'), ('Цитаты реально-существующих', 'Цитаты реально-существующих')], default='Книга', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='source_name',
            field=models.CharField(default='Книга', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
