# Generated by Django 5.2.6 on 2025-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_quote_source_quote_author_name_quote_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статистика сайта',
                'verbose_name_plural': 'Статистика сайта',
            },
        ),
    ]
