# Generated by Django 5.2.6 on 2025-09-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_sitestats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestats',
            options={},
        ),
    ]
